Repository OpenVoiceOS/ovos-ocp-audio-plugin, pull requests merged in 2023-04, with the labels that each got.

#69 Bugfixes and Unit Tests
  ovos_plugin_common_play/ocp/__init__.py
  ovos_plugin_common_play/ocp/media.py
  ovos_plugin_common_play/ocp/player.py
  test/unittests/test_ocp.py
  test/unittests/test_ocp_media.py
  test/unittests/test_ocp_player.py
Labels: bug

#72 mycroft-bus-client -> ovos-bus-client
  ovos_plugin_common_play/__init__.py
  ovos_plugin_common_play/ocp/base.py
  ovos_plugin_common_play/ocp/gui.py
  ovos_plugin_common_play/ocp/mpris.py
  ovos_plugin_common_play/ocp/mycroft_cps.py
  requirements/requirements.txt
  test/unittests/test_mycroft.py
Labels: refactor

#76 Update Automations and Dependencies
  .github/workflows/dev2master.yml
  .github/workflows/propose_release.yml
  .github/workflows/publish_alpha.yml
  .github/workflows/publish_build.yml
  .github/workflows/publish_major.yml
  .github/workflows/publish_minor.yml
  .github/workflows/publish_release.yml
  requirements/requirements.txt
  scripts/bump_alpha.py
  scripts/bump_build.py
  scripts/bump_major.py
  scripts/bump_minor.py
  scripts/remove_alpha.py
Labels: automation and testing

#77 Fix automation typos
  .github/workflows/propose_release.yml
  .github/workflows/publish_alpha.yml
Labels: automation and testing

#80 Replace mycroft_bus_client with ovos_bus_client
  ovos_plugin_common_play/ocp/media.py
  test/unittests/test_ocp.py
  test/unittests/test_ocp_media.py
  test/unittests/test_ocp_player.py
Labels: enhancement
